### ISSUE TITLE
Add termination notice handling

### ISSUE THREAD

**Issue by tarasglek** [cablespaghetti/kubeadm-aws#1]
This is cool.
One improvement is to add a termination-notice handler to trigger backup(ala https://blog.fugue.co/2015-01-06-spot-termination-notices.html).
 Ec2 gives you a 2min termination notice, which should be plenty.

**Comment by cablespaghetti** [comment]
I did see that was a feature. I wouldn't necessarily want to rely on it as the sole thing that triggers a backup. However, maybe I'll make the scheduled backup interval a parameter so you can make it more infrequent if you want and then add this.

**Comment by cablespaghetti** [comment]
I'm going to call this done, although I'm not sure how to verify that it is working correctly other than wait around for my instance to eventually get terminated by AWS...
