### ISSUE TITLE
Work out reliable way of generating tokens

### ISSUE THREAD

**Issue by cablespaghetti** [cablespaghetti/kubeadm-aws#5]
The current python one-liner seems to be unreliable. Some scripting may be in order.

https://github.com/upmc-enterprises/kubeadm-aws/issues/11

**Comment by vegardx** [comment]
https://www.terraform.io/docs/providers/random/index.html

**Comment by cablespaghetti** [comment]
Thanks, I didn't know about this provider :+1:
