### ISSUE TITLE
Error during during terraform apply

### ISSUE THREAD

**Issue by buker** [cablespaghetti/kubeadm-aws#8]
```
terraform version
Terraform v0.11.11
+ provider.aws v1.58.0
+ provider.template v2.0.0

```
Error from terraform apply command:
```

Error: Error refreshing state: 1 error(s) occurred:

* data.template_file.master-userdata: 1 error(s) occurred:

* data.template_file.master-userdata: data.template_file.master-userdata: failed to render : <template_file>:162,46-55: Invalid template control keyword; "http_code" is not a valid template control keyword.

```

After that it is imposible to destroy or reapply state. 
Plan works correctly.

**Comment by kgorskowski** [comment]
Seems like Terraform changed the templating syntax a bit, from the [changelog](https://github.com/terraform-providers/terraform-provider-template/blob/master/CHANGELOG.md#200-january-14-2019) 

> HCL 2.0 template syntax includes a new %{ ... } construct for control structures, like %{ if a == b } ... %{ endif }. If your existing templates contain any %{ sequences you will need to now escape them as %%{ to ensure correct parsing.
this fixed it for me

**Comment by hmain** [comment]
Hi,
I've got the same issue.

```
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.template v2.0.0
```

Offending line:
`while http_status=$(curl -o /dev/null -w '%{http_code}' -sL $${NOTICE_URL}); [ $${http_status} -ne 200 ]; do`

Probably has to do with https://github.com/terraform-providers/terraform-provider-template/issues/50 but I cannot find a similar workaround.

**Comment by jasisk** [comment]
Fix is to either pin the template provider to `~> 1.0` or to pin it to `~> 2.0` and update the template with (notice the doubling in `%%`):
```
while http_status=$(curl -o /dev/null -w '%%{http_code}' -sL $${NOTICE_URL}); [ $${http_status} -ne 200 ]; do
```

**Comment by cablespaghetti** [comment]
Thanks guys. Sorry for the slow action.

**Comment by jasisk** [comment]
No need for apology. Thanks to you for doing stuff for us _for free_.
